### ISSUE TITLE
Lack of clean-layout menu button and shortcut keys for subflowcharts

### ISSUE THREAD

**Issue by SinaMostafanejad** [molssi-seamm/seamm#113]
* MolSSI Workflow version: 2021.9.11
* Python version: 3.9
* Operating System: Linux Ubuntu 18.04 LTS

### Description

For **subflowcharts** such as that of _dftbplus_step_, an _edit/clean layout_ menu button is missing and the user cannot clean the layout, even using shortcut keys.

**Comment by seamm** [comment]
Closed because 2024.11.1 resolves this issue
